### ISSUE TITLE
How to launch WAL script ?

### ISSUE THREAD

**Issue by Martoni** [ics-jku/wal#29]
Hello,

I'm trying to launch the following WAL script with version (0.8.1).
`waltry.wal` : 
```lisp
(define wait 0)
(define packets 0)
(whenever (rising clk)
          (when (&& req (! ack)) (inc wait))
          (when (&& req ack) (inc packets)))
(print (/ wait packets))
```
With VCD file provided in tutorial `fdl.vcd` .

The following command return nothing : 
```shell
$ wal -l fdl.vcd -c waltry.wal
```

Even if I insert error in file nothing is returned.

**Comment by LucasKl** [comment]
Hi,
try `wal -l fdl.vcd waltry.wal`.

**Comment by Martoni** [comment]
Thanks @LucasKl

In fact, the right command is with wal script as first argument : 

```shell
$ wal waltry.wal -l fdl.vcd

>>>>> WAL Runtime error! <<<<<
 1: (define wait 0)
 2: (define packets 0)
 3: (whenever (rising clk)
 4:           (when (&& req (! ack)) (inc wait))
 5:           (when (&& req ack) (inc packets)))

```

The error is from code, if I try simplest following program It works : 

```lisp
(print "pof")
```

```shell
$ wal pof.wal -l fdl.vcd 
pof
```

If script name is given at the end of command it doesn't work : 

```shell
$ wal -l fdl.vcd pof.wal
File extension ".wal" not supported.
WAL 0.8.1
Exit to OS or terminate running evaluations with CTRL-C
t0(0) >-> 
```

**Comment by LucasKl** [comment]
Oh right, the order is important. Good that it works now. If something comes up, feel free to contact me. :)
