### ISSUE TITLE
WAL should support FST

### ISSUE THREAD

**Issue by eyck** [ics-jku/wal#3]
The WAL kernel should be able to read also FST files as they are much more faster to read and consume less disk space

**Comment by LucasKl** [comment]
This is very high on our TODO list. I will look into it after I get back from my vacation :)

**Comment by LucasKl** [comment]
WAL now supports the fst format.
FST files can be opened with the load function, just like with vcd files.
Compared to vcd, fst does not suffer from the memory explosion problem and are very nice for huge traces.
